import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Fitness Aibou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-gray-950 from-25% via-gray-600 via-65% to-gray-500 to-90%`}
      >
        {/*<NavBar/>*/}
        {children}
      </body>
    </html>
  );
}
