import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "My Fitness Aibou - Signup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="h-full bg-gradient-to-r from-gray-950 from-25% via-gray-600 via-65% to-gray-500 to-90%"
    >
      <body className="h-full">{children}</body>
    </html>
  );
}
