import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "My Fitness Aibou - Signup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className="h-full">{children}</body>
    </html>
  );
}
